# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
  end

  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.boot_timeout = 600

  nodes = {
    master:  { memory: 4096, cpus: 2 },
    worker1: { memory: 2048, cpus: 2 },
    worker2: { memory: 2048, cpus: 2 }
  }

  nodes.each do |name, params|
    config.vm.define name do |node|
      node.vm.hostname = name.to_s

      # Don't define any network: default libvirt network will be used

      node.vm.provider :libvirt do |libvirt|
        libvirt.memory = params[:memory]
        libvirt.cpus   = params[:cpus]
      end

      node.vm.provision "shell", inline: <<-SHELL
        hostnamectl set-hostname #{name}
        apt-get update -y
        apt-get install -y python3 python3-apt pip
      SHELL
    end
  end
end

